apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multik8span-com-tls
spec:
  secretName: multik8span-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multik8span.com
  dnsNames:
    - multik8span.com
    - www.multik8span.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multik8span.com
          - www.multik8span.com
